### ISSUE TITLE
Error:convert_bfm09_data.py

### ISSUE THREAD

**Issue by sablea** [ascust/3DMM-Fitting-Pytorch#15]
I try to use colab to run the code
I use the same data as readme.md
When i execute “!python convert_bfm09_data.py”，I get the following error:

Traceback (most recent call last):
  File "convert_bfm09_data.py", line 102, in <module>
    transferBFM09()
  File "convert_bfm09_data.py", line 38, in transferBFM09
    expPC, expEV = LoadExpBasis()
  File "convert_bfm09_data.py", line 15, in LoadExpBasis
    expMU.fromfile(Expbin, 3*n_vertex)
ValueError: bytes length not a multiple of item size

**Comment by sablea** [comment]
forget it.I solve the problem.I'm not very proficient in the way GitHub is used.
I used the link "https://github.com/Juyong/3DFace/blob/master/Exp_Pca.bin" to download Exp_Pca.bin.This is wrong
I should use "https://github.com/Juyong/3DFace/raw/master/Exp_Pca.bin" to download
